api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects, name="api-projects"), # the name is prefixed with "api-" to prevent name clash with the normal 'projects' route
    path('projects/<str:pk>/', views.getProject, name="api-project"), # the name is prefixed with "api-" to prevent name with the normal 'project' routes
    path('projects/<str:pk>/vote/', views.projectVote, name="vote"),
]

# Although it makes more sense to use the route as project/<str:pk>, but to keep the API more
# Restful, we are going to use the "projects/<str:pk>" instead of "project/<str:pk>" as the route

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# this is going to help create a url for our static files
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# MEDIA_ROOT is where we sent out user uploaded content to and now with the above line we are creating a path for each image


# 1. User submits email for reset           // PasswordResetView..as_view()
# 2. Email sent message                     // PasswordResetDoneView.as_view()
# 3. Email with link and reset instructions // PasswordResetConfirmView.as_view()
# 4. Password successfully reset message    // PasswordResetCompleteView.as_view()

users/urls.py
from django.urls import path
# since we are importing the views within the same directory, we can use "."
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),

    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('account/', views.userAccount, name="account"),

    path("edit-account/", views.editAccount, name="edit-account"),

    path("create-skill/", views.createSkill, name="create-skill"),
    path('update-skill/<str:pk>/', views.updateSkill, name="update-skill"),
    path('delete-skill/<str:pk>/', views.deleteSkill, name="delete-skill"),
    
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:pk>/', views.createMessage, name="create-message"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.
class Project(models.Model):
    # using foreignKey creates a many to one relationship - one profile can have many projects
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE) 
    # SET_NULL will not delete the projects when the profile is deleted
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_count = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        # ordering helps us specify the attributes by which the model instances are ordered
        # using a minus sign reverses the ordering (be default is ascending, adding "-" makes it descending)
        # using more than one value to perform ordering means, if there is a tie in ordering based on the first value, 
        # then the second value is used to break the tie and so on and so forth using the subsequent values
        ordering = ["-vote_ratio", "-vote_count", 'title']
        # here the ordering is based on highest vote ratio first and if there is a tie, the highest votes,
        # and if there is a tie even after that, we use alphabetical ordering of the title (note the lack of minus in the title)

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ""
        return url

    @property
    def reviewers(self):
        # getting a list of reviewers
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        # flat = True does not return a list of tuples, rather a plain list
        # https://stackoverflow.com/questions/37205793/django-values-list-vs-values
        # check the link above to get more clarity on values_list(p) vs values()
        return queryset

    # the @property decorator allows the function to be called as a class property than a function call
    # so to get execute the function, we will say project.updateVoteCount instead of project.updateVoteCount() with the parentheses
    @property
    def updateVoteCount(self):
        # getting all the required values
        reviews = self.review_set.all()
        upVotes = reviews.filter(value="up").count()
        totalVotes = reviews.count()

        # calculating the required values
        voteRatio = int((upVotes / totalVotes) * 100) # calculating the percentage and casting it to integer
        
        # updating the model values
        self.vote_count = totalVotes
        self.vote_ratio = voteRatio

        # saving the updated values
        self.save()


class Review(models.Model):
    # VOTE_TYPE provides a tuple of tuples to use as the only available choices
    # the first element in the inner tuple is for string representation in the admin panel
    # the second element in the inner tuple is for the options shown to the user in dropdown and also in admin panel
    VOTE_TYPE = (
        ('up', 'Upvote'),
        ('down', 'Downvote')
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True) 
    project = models.ForeignKey(Project, on_delete=models.CASCADE) 
    # if a project is deleted, then its corresponding reviews will be deleted too
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE) # only two choices for the value column
    created = models.DateTimeField(auto_now_add=True) 
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        # this unique_together makes sure that each user (or profile) can only leave one review per project
        # by this condition we are making sure that no user will leave more than one review per project
        # note that unique_together is a list of lists, each inner list is a combination of fields that are unique together
        unique_together = [['owner', 'project']]

    # the def __str__ is basically like the toString method in Java. It overrrides the default string version of any object
    # in java, if we try to print an object, the hexadecimal address of the object gets logged in the console
    # but the toString method helps to give the object a more human readable format of printing or displaying
    # the __str__ in python exactly serves the same purpose
    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Profile(models.Model):
    # everytime a user is deleted, its corresponding profile will be deleted too
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to="profiles/", default="profiles/user-default.png")

    # social media links
    social_github = models.CharField(max_length=500, null=True, blank=True)
    social_stackoverflow = models.CharField(max_length=500, null=True, blank=True)
    social_twitter = models.CharField(max_length=500, null=True, blank=True)
    social_linkedin = models.CharField(max_length=500, null=True, blank=True)
    social_youtube = models.CharField(max_length=500, null=True, blank=True)
    social_website = models.CharField(max_length=500, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        # if you happen to use a number field for the string representation, then make sure to cast to string
        return str(self.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name


class Message(models.Model):
    # sender is the person sending the message
    # sender does not need to have a user account with devsearch to send a message, hence the null = True and blank = True
    # if a sender deletes their profile, the recipient should still be able to see the messages, hence the models.SET_NULL
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)

    # recipient is the person receiving the message
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    # django DOES NOT allow us to have two fields that access the same foreign key, so we need to have 
    # atleast one of those fields to have a related_name attribute and this will solve that issue
    # related_name helps us in accessing the property somewhat differently
    # without a related name, we use the profile.message_set.all()
    # with a related name, we use profile.messages(), assuming that the related name is "messages"
    
    # we want a name regardless of the sender having a user account or not
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField(max_length=1000, null=True) # we dont a blank message, so did not set blank=True
    is_read = models.BooleanField(default=False, null=True) # represents whether the message is read or not
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    # explanation for null = True and blank = True and their differences
    # https://stackoverflow.com/questions/8609192/what-is-the-difference-between-null-true-and-blank-true-in-django

    def __str__(self):
        return self.subject

    # ordering the messages by unread messages first and within the unread or read messages we use latest to oldest order for messages
    class Meta:
        ordering = ['is_read', '-created']
    

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Skill, Message

# inheriting from the UserCreationForm provides us with all the attributes and methods of that ModelForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        # password1 refers to the password and password2 refers to the password confirmation
        fields = ['first_name', "email", "username", "password1", "password2"]
        labels = {
            'first_name': 'Name'
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        # this method of updating the form fields individually is very lengthy and cumbersome
        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': "Add Title"})
        # self.fields['description'].widget.attrs.update({'class': 'input', 'placeholder': "Add a detailed description"})

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username', 'location', 'short_intro', 'bio', 'profile_image', 'social_github',
                  'social_stackoverflow', 'social_twitter', 'social_linkedin', 'social_youtube', 'social_website']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        # this method of updating the form fields individually is very lengthy and cumbersome
        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': "Add Title"})
        # self.fields['description'].widget.attrs.update({'class': 'input', 'placeholder': "Add a detailed description"})

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        # the __all__ uses all the fields excluding the ones declared by the exclude array below
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']
        labels = {
            'body': 'Message'
        }

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i>
              Edit</a>
            <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
            <h2 class="dev__name">{{ profile.name }}</h2>
            <p class="dev__title">{{ profile.short_intro }}</p>
            <p class="dev__location">Based in {{ profile.location }}</p>
            <ul class="dev__social">
              {%if profile.social_github %}
              <li>
                <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
              </li>
              {% endif %}
              {%if profile.social_stackoverflow %}
              <li>
                <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i
                    class="im im-stackoverflow"></i></a>
              </li>
              {% endif %}
              {%if profile.social_twitter %}
              <li>
                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
              </li>
              {% endif %}
              {%if profile.social_linkedin %}
              <li>
                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i
                    class="im im-linkedin"></i></a>
              </li>
              {% endif %}
              {%if profile.social_website %}
              <li>
                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i
                    class="im im-globe"></i></a>
              </li>
              {% endif %}
            </ul>
            <!-- <a href="#" class="btn btn--sub btn--lg">Send Message </a> -->
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">
            {{profile.bio}}
          </p>
        </div>
        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i
              class="im im-plus"></i> Add Skill</a>
        </div>

        <table class="settings__table">
          {% for skill in skills %}
          <tr>
            <td class="settings__tableInfo">
              <h4>{{skill.name}}</h4>
              <p>{{skill.description|slice:"150"}}...</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i
                  class="im im-edit"></i> Edit</a>
              <!-- the ?next=/account helps in forming the dynamic links for going back to different pages when using the reusable delete template  -->
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i
                  class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          {% endfor %}
        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i
              class="im im-plus"></i> Add Project</a>
        </div>

        <table class="settings__table">
          {% for project in projects %}
          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'project' project.id %}"><img src="{{project.imageURL}}"
                  alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'project' project.id %}">{{project.title}}</a>
              <p>{{project.description|slice:"150"}}...</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i
                  class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn"
                href="{% url 'delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          {% endfor %}

        </table>
      </div>
    </div>
  </div>
</main>

{% endblock content%}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
    {% if messageRequests.count == 0%}
    <p>You have no messages !</p>
    {% else %}
    <ul class="messages">
      {% for message in messageRequests %}
      {% if message.is_read == False %}
      <li class="message message--unread">
        {% else %}
      <li class="message">
        {% endif %}
        <a href="{% url 'message' message.id %}">
          <span class=" message__author">{{ message.name }}</span>
          <span class="message__subject">{{message.subject}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>

      {% endfor %}

      {% endif %}
    </ul>
  </div>
</main>

{% endblock content %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
      <h2 class="message__subject">{{message.subject}}</h4>
        <a href="profile.html" class="message__author">{{message.name}}</a>
        <p class="message__date">{{message.created}}</p>
        <div class="message__body">
          {{message.body|linebreaksbr}}
        </div>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">
                <form class="form" id="searchForm" action="{% url 'profiles' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Search by developer name, intro or skills" value="{{search_query}}" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">

                {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'user-profile' profile.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                                <div class="dev__meta">
                                    <h3>{{ profile.name }}</h3>
                                    <h5>{{ profile.short_intro | slice:"50" }}</h5>
                                </div>
                            </div>
                            <p class="dev__info">{{ profile.bio | slice:"150" }}</p>

                            <div class="dev__skills">
                                <!-- the slice function outputs only 5 skills if ther user has more than 5 skills -->
                                {% for skill in profile.skill_set.all|slice:"5" %}
                                <span class="tag tag--pill tag--main">
                                    <small>{{ skill }}</small>
                                </span>
                                {% endfor %}
                            </div>
                        </a>
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>
    </section>
</main>

{% include 'pagination.html' with query_set=profiles custom_range=custom_range paginator=paginator %}

{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}


{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">{{profile.short_intro}}</p>
                        <p class="dev__location">Based in {{profile.location}}</p>
                        <ul class="dev__social">
                            {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{ profile.social_github }}" target="_blank"><i
                                        class="im im-github"></i></a>
                            </li>
                            {% endif%}
                            {% if profile.social_stackoverflow %}
                            <li>
                                <a title="Stackoverflow" href="{{ profile.social_stackoverflow }}" target="_blank"><i
                                        class="im im-stackoverflow"></i></a>
                            </li>
                            {% endif%}
                            {% if profile.social_twitter %}
                            <li>
                                <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i
                                        class="im im-twitter"></i></a>
                            </li>
                            {% endif%}
                            {% if profile.social_linkedin %}
                            <li>
                                <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i
                                        class="im im-linkedin"></i></a>
                            </li>
                            {% endif%}
                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i
                                        class="im im-globe"></i></a>
                            </li>
                            {% endif%}
                        </ul>

                        <!-- DONT display send message button only for the currently logged in users' own profile -->
                        {% if request.user.profile.id != profile.id %}
                        <a href="{% url 'create-message' profile.id %}" class=" btn btn--sub btn--lg">Send
                            Message </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">{{ profile.bio }}</p>
                </div>
                <div class="devInfo">
                    {% if topSkills|length %}
                    <h3 class="devInfo__title">Skills</h3>
                    {% endif %}
                    <div class="devInfo__skills">
                        {% for topSkill in topSkills %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{topSkill}}</h4>
                            <p class="devSkill__info">{{ topSkill.description }}</p>
                        </div>
                        {% endfor %}

                        {% if otherSkills|length %}
                        <h3 class="devInfo__subtitle">Other Skills</h3>
                        {% endif %}
                        <div class="devInfo__otherSkills">
                            {% for otherSkill in otherSkills %}
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>{{ otherSkill }}</small>
                            </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Projects</h3>
                    <div class="grid grid--two">

                        {% for project in profile.project_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'project' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{ project.imageURL }}"
                                        alt="project thumbnail" />
                                    <div class="card__body">
                                        <h3 class="project__title">{{project.title}}</h3>
                                        <p><a class="project__author"
                                                href="{% url 'user-profile' project.owner.id %}">By
                                                {{project.owner.name}}</a>
                                        </p>
                                        <p class="project--rating">
                                            <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Positive
                                            Feedback ({{project.vote_count}} Vote{{ project.vote_count|pluralize:"s" }})
                                        </p>
                                        <div class="project__tags">
                                            {% for tag in project.tags.all %}
                                            <span class="tag tag--pill tag--main">
                                                <small>{{tag}}</small>
                                            </span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}